CREATE OR REPLACE PROCEDURE UPDATESALARY (
    ID  IN NUMBER,
    PER IN NUMBER
) IS
BEGIN
    UPDATE EMPLOYEES
    SET
        SALARY = SALARY + SALARY * ( PER / 100 )
    WHERE
        ID = EMPLOYEEID;

    IF SQL%ROWCOUNT = = 0 THEN
        RAISE NO_DATA_FOUND;
    END IF;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE("Noo data found");
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/