CREATE OR REPLACE PROCEDURE UPDATEEMPLOYEEBONUS (
    BONUS       IN NUMBER,
    PDEPARTMENT IN VARCHAR2
) AS
BEGIN
    UPDATE EMPLOYEES
    SET
        SALARY = SALARY + ( SALARY * BONUS / 100 )
    WHERE
        DEPARTMENT = PDEPARTMENT;

END;
/