CREATE OR REPLACE FUNCTION HASSUFFICIENTBALANCE (
    T_ACCOUNTID IN NUMBER,
    AMOUNT      IN NUMBER
) RETURN VARCHAR AS
    TBALANCE NUMBER;
BEGIN
    SELECT
        BALANCE
    INTO TBALANCE
    FROM
        ACCOUNTS
    WHERE
        ACCOUNTID = T_ACCOUNTID;

    IF ( TBALANCE >= AMOUNT ) THEN
        RETURN 'true';
    ELSE
        RETURN 'false';
    END IF;
END;
/