CREATE OR REPLACE FUNCTION CALCULATEMONTHLYINSTALLMENT (
    L_AMOUNT      IN NUMBER,
    INTREST_RATE  IN NUMBER,
    LOAN_DURATION IN NUMBER
) RETURN NUMBER AS
    TOTAL NUMBER;
BEGIN
    TOTAL := L_AMOUNT + ( L_AMOUNT * INTREST_RATE * LOAN_DURATION ) / 100;
    RETURN L_AMOUNT / ( LOAN_DURATION * 12 );
END;
/