CREATE OR REPLACE TRIGGER LOGTRANSACTION AFTER
    INSERT ON TRANSACTIONS
    FOR EACH ROW
BEGIN
    INSERT INTO AUDITLOG (
        TRANSACTIONID,
        ACTION,
        ACTIONDATE
    ) VALUES ( :NEW.TRANSACTIONID,
               'INSERT',
               SYSDATE );

END;
/